version: '3.1'

services:
  postgres:
    image: postgres:10
    container_name: my_postgres_container2
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=chatapp
    ports:
      - "5433:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"


volumes:
  my_postgres_data:


